#!/usr/bin/env bash
# install-hooks.sh — install git quality-gate hooks for both the SmartHomeNG
# core repository and the plugins repository in a single call.
#
# Usage:
#   tools/install-hooks.sh [PLUGINS_DIR]
#
# PLUGINS_DIR defaults to ./plugins (relative to the shng root).
# Override if your plugins checkout lives elsewhere:
#   tools/install-hooks.sh /path/to/smarthomeng-plugins
#
# What the script does:
#   shng repo  — activates the committed .githooks/ directory via
#                  git config core.hooksPath .githooks
#   plugins repo — writes post-commit and pre-push hooks directly into
#                  PLUGINS_DIR/.git/hooks/ and makes them executable.
#                  Both hooks cd into the shng root before running ruff/pytest
#                  so that import paths and pyproject.toml are always found.
#
# To update plugin hooks after changes to this script, simply re-run it.

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate shng root (script may be called from any working directory)
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHNG_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ ! -f "$SHNG_DIR/tox.ini" ] || [ ! -d "$SHNG_DIR/lib/item" ]; then
    echo "ERROR: $SHNG_DIR does not look like a SmartHomeNG root (tox.ini / lib/item missing)."
    exit 1
fi

# ---------------------------------------------------------------------------
# Locate plugins repo
# ---------------------------------------------------------------------------
PLUGINS_DIR="${1:-$SHNG_DIR/plugins}"
PLUGINS_DIR="$(cd "$PLUGINS_DIR" && pwd)"   # normalise to absolute path

if [ ! -d "$PLUGINS_DIR/.git" ]; then
    echo "ERROR: $PLUGINS_DIR is not a git repository (.git directory not found)."
    echo "Pass the correct path as the first argument: tools/install-hooks.sh /path/to/plugins"
    exit 1
fi

# ---------------------------------------------------------------------------
# ruff / pytest discovery helpers (baked into generated hooks at install time)
# ---------------------------------------------------------------------------
RUFF_BIN="${SHNG_DIR}/venvs/shng/bin/ruff"
PYTEST_BIN="${SHNG_DIR}/venvs/shng/bin/pytest"

echo ""
echo "SmartHomeNG git hook installer"
echo "  shng root   : $SHNG_DIR"
echo "  plugins root: $PLUGINS_DIR"
echo "  ruff        : $([ -x "$RUFF_BIN" ] && echo "$RUFF_BIN" || echo "ruff (from PATH)")"
echo "  pytest      : $([ -x "$PYTEST_BIN" ] && echo "$PYTEST_BIN" || echo "pytest (from PATH)")"
echo ""

# ---------------------------------------------------------------------------
# 1. shng repo — activate committed .githooks/
# ---------------------------------------------------------------------------
echo "=== shng: activating .githooks/ ==="

SHNG_HOOKS_DIR="$SHNG_DIR/.githooks"
if [ ! -d "$SHNG_HOOKS_DIR" ]; then
    echo "  ERROR: $SHNG_HOOKS_DIR not found — has the repo been cloned completely?"
    exit 1
fi

chmod +x "$SHNG_HOOKS_DIR/post-commit" "$SHNG_HOOKS_DIR/pre-push"
git -C "$SHNG_DIR" config core.hooksPath .githooks
echo "  git config core.hooksPath .githooks  → done"
echo "  hooks: post-commit (informational), pre-push (blocking)"
echo ""

# ---------------------------------------------------------------------------
# 2. plugins repo — write hooks into .git/hooks/
# ---------------------------------------------------------------------------
echo "=== plugins: writing hooks to $PLUGINS_DIR/.git/hooks/ ==="

PLUGIN_HOOKS_DIR="$PLUGINS_DIR/.git/hooks"

# -- post-commit (informational) -------------------------------------------
cat > "$PLUGIN_HOOKS_DIR/post-commit" << HOOK
#!/usr/bin/env bash
# post-commit — informational ruff + pytest run after every commit.
# Never exits non-zero: the commit already landed; pre-push is the hard gate.
# Generated by tools/install-hooks.sh — re-run that script to update.

SHNG_DIR="${SHNG_DIR}"
cd "\$SHNG_DIR" || exit 0

RUFF="${RUFF_BIN}"
[ -x "\$RUFF" ] || RUFF="ruff"
PYTEST="${PYTEST_BIN}"
[ -x "\$PYTEST" ] || PYTEST="pytest"

echo ""
echo "── post-commit (plugins) ───────────────────────────────────────"

if "\$RUFF" check plugins/ --quiet 2>&1; then
    echo "  ruff  : OK"
else
    echo "  ruff  : issues found — run 'ruff check plugins/' from shng root to review"
fi

"\$PYTEST" --tb=no -q 2>&1 | tail -4

echo "────────────────────────────────────────────────────────────────"
echo ""
exit 0
HOOK

# -- pre-push (blocking) ---------------------------------------------------
cat > "$PLUGIN_HOOKS_DIR/pre-push" << HOOK
#!/usr/bin/env bash
# pre-push — ruff + pytest must both pass before a push is allowed.
# Generated by tools/install-hooks.sh — re-run that script to update.

SHNG_DIR="${SHNG_DIR}"
cd "\$SHNG_DIR" || exit 1

RUFF="${RUFF_BIN}"
[ -x "\$RUFF" ] || RUFF="ruff"
PYTEST="${PYTEST_BIN}"
[ -x "\$PYTEST" ] || PYTEST="pytest"

echo ""
echo "── pre-push gate (plugins) ─────────────────────────────────────"

if ! "\$RUFF" check plugins/; then
    echo ""
    echo "  PUSH REJECTED: fix ruff errors first ('ruff check plugins/' from shng root)"
    echo "────────────────────────────────────────────────────────────────"
    echo ""
    exit 1
fi
echo "  ruff  : OK"

if ! "\$PYTEST" --tb=short -q; then
    echo ""
    echo "  PUSH REJECTED: fix failing tests first"
    echo "────────────────────────────────────────────────────────────────"
    echo ""
    exit 1
fi
echo "  pytest: OK"

echo "────────────────────────────────────────────────────────────────"
echo ""
HOOK

chmod +x "$PLUGIN_HOOKS_DIR/post-commit" "$PLUGIN_HOOKS_DIR/pre-push"
echo "  post-commit (informational) → written"
echo "  pre-push    (blocking)      → written"
echo ""

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo "Installation complete."
echo ""
echo "Both hooks cd into the shng root before running ruff/pytest, so"
echo "import paths and pyproject.toml are always resolved correctly."
echo ""
echo "To skip the pre-push gate for a specific push (use sparingly):"
echo "  git push --no-verify"
echo ""
